name: vps
services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN #Linux capabilities
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Europe/moscow
      - URL=salihof.ru
      - VALIDATION=http
      - SUBDOMAINS=www,wiki,str,ars
        # - CERTPROVIDER= #optional
        # - DNSPLUGIN=cloudflare #optional
        # - DUCKDNSTOKEN=<token> #optional
        # - EMAIL=<e-mail> #optional
      - ONLY_SUBDOMAINS=false #optional
        # - EXTRA_DOMAINS=<extradomains> #optional
        # - STAGING=false #optional
    volumes:
      - /vlm_docker/swag/config:/config
    networks:
      mynet:
        ipv4_address: 172.22.0.11
    ports:
      - 443:443
      - 80:80 #optional, required for http validation only
    restart: unless-stopped
    command: /bin/bash -c "ip route add 172.24.0.0/24 dev eth0 via 172.22.0.13 || true; exec /init"


  # dokuwiki:
  #   image: lscr.io/linuxserver/dokuwiki:latest
  #   container_name: dokuwiki
  #   environment:
  #     - PUID=1001
  #     - PGID=100
  #     - TZ=europe/moscow
  #   volumes:
  #     - /vlm_docker/dokuwiki/config:/config    
  #   networks:
  #     mynet:
  #       ipv4_address: 172.22.0.12
  #   depends_on:
  #     - swag
  #   restart: unless-stopped


networks:
  mynet:
    name: mynet
    external: true

